version: "3.9"  # optional since v1.27.0
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: test
      PGDATA: /data/postgres
    ports:
      - "5432:5432"